"""The exporter and the Grafana dashboard are a contract written down in two
places: prom.py names the metrics, hft-engine.json queries them by name. Until
now nothing tied the two together, so renaming a metric -- or dropping a label
the dashboard groups by -- broke the dashboard silently and only at the point
someone opened it.

These tests read the dashboard JSON that ships in this repo, pull every metric
name and every label it selects or groups by out of the PromQL, and check them
against what the registry actually exposes after the recording helpers have
run. A rename now fails CI instead.
"""

from __future__ import annotations

import json
import re
from pathlib import Path

import pytest

from hft.metrics import prom
from hft.metrics.timing import LatencySample

DASHBOARD = Path(__file__).resolve().parents[1] / "monitoring" / "grafana" / "dashboards" / "hft-engine.json"

# Suffixes the exposition format adds to a metric's base name. The dashboard
# queries the exposed names, so they are what has to match.
_METRIC_RE = re.compile(r"\bhft_[a-z0-9_]+\b")
# `metric{label=...` -- a label selected on a specific metric.
_SELECTOR_RE = re.compile(r"\b(hft_[a-z0-9_]+)\{([^}]*)\}")
_LABEL_IN_SELECTOR_RE = re.compile(r"([a-z_]+)\s*(?:=~|!~|=|!=)")
# `sum by (label) (...)` -- a grouping applied to whatever the expression reads.
_BY_RE = re.compile(r"\bby\s*\(([^)]*)\)")

# `le` is generated by the histogram itself, not by our label choices.
_IMPLICIT_LABELS = {"le"}


def _expressions() -> list[str]:
    doc = json.loads(DASHBOARD.read_text(encoding="utf-8"))
    found: list[str] = []

    def walk(node) -> None:
        if isinstance(node, dict):
            expr = node.get("expr")
            if isinstance(expr, str):
                found.append(expr)
            for value in node.values():
                walk(value)
        elif isinstance(node, list):
            for value in node:
                walk(value)

    walk(doc)
    return found


def _exposed() -> dict[str, set[str]]:
    """Exposed sample name -> the label names carried on that sample.

    Every recording helper is driven first, because a labelled metric with no
    child yet exposes no samples at all -- and a dashboard querying a label
    that no code path ever sets is exactly the bug worth catching.
    """
    prom.record_tick("AAPL", 191.23)
    prom.record_buffer_state(depth=3, dropped_total=1)
    prom.record_feed_error(TimeoutError("slow"))
    prom.record_signal("BUY")
    prom.record_order_submitted("BUY")
    prom.record_order_filled("BUY", 10)
    prom.record_order_rejected("ValueError")
    prom.record_venue_state({"AAPL": 10}, realized_pnl=42.5)
    prom.observe_latency_sample(
        LatencySample(ingest_to_signal_ns=1_500, signal_compute_ns=800, order_round_trip_ns=250_000)
    )

    out: dict[str, set[str]] = {}
    for family in prom.REGISTRY.collect():
        for sample in family.samples:
            out.setdefault(sample.name, set()).update(sample.labels.keys())
    return out


@pytest.fixture(scope="module")
def exposed() -> dict[str, set[str]]:
    return _exposed()


def test_dashboard_file_exists_and_has_queries():
    assert DASHBOARD.is_file()
    exprs = _expressions()
    assert len(exprs) > 20  # the dashboard is not empty or half-parsed


def test_every_metric_the_dashboard_queries_is_exported(exposed):
    referenced = {name for expr in _expressions() for name in _METRIC_RE.findall(expr)}
    assert referenced, "no hft_* metrics found in the dashboard -- parsing broke"
    missing = sorted(referenced - set(exposed))
    assert not missing, f"dashboard queries metrics the exporter does not expose: {missing}"


def test_every_label_the_dashboard_uses_is_exported(exposed):
    problems: list[str] = []
    for expr in _expressions():
        metrics = set(_METRIC_RE.findall(expr))

        for metric, selector in _SELECTOR_RE.findall(expr):
            for label in _LABEL_IN_SELECTOR_RE.findall(selector):
                if label in _IMPLICIT_LABELS:
                    continue
                if label not in exposed.get(metric, set()):
                    problems.append(f"{metric} has no label {label!r} (selector in: {expr})")

        # A `by (label)` has to be satisfiable by every hft_ metric the same
        # expression reads, since that is what it groups.
        for group in _BY_RE.findall(expr):
            for label in (part.strip() for part in group.split(",")):
                if not label or label in _IMPLICIT_LABELS:
                    continue
                for metric in metrics:
                    if label not in exposed.get(metric, set()):
                        problems.append(f"{metric} has no label {label!r} (grouped in: {expr})")

    assert not problems, "dashboard/exporter label mismatch:\n" + "\n".join(sorted(set(problems)))


def test_exporter_uses_its_own_registry():
    # The default global registry also carries process/GC collectors, and
    # anything else in the process that imports prometheus_client. A dedicated
    # registry keeps /metrics to this pipeline's own series.
    import prometheus_client

    assert prom.REGISTRY is not prometheus_client.REGISTRY


def test_dropped_ticks_counter_takes_the_delta_not_the_total():
    # RingBuffer owns `dropped` as a running total; inc()-ing the total would
    # compound it into a number that climbs quadratically.
    prom.record_buffer_state._last_dropped = 0
    prom.TICKS_DROPPED._value.set(0)

    prom.record_buffer_state(depth=1, dropped_total=5)
    prom.record_buffer_state(depth=1, dropped_total=8)
    prom.record_buffer_state(depth=1, dropped_total=8)  # nothing new dropped

    assert prom.TICKS_DROPPED._value.get() == 8


def test_latency_samples_are_exported_in_seconds():
    # Prometheus convention is base units, and the dashboard's histogram
    # quantiles are labelled in seconds. The recorder works in nanoseconds.
    before = prom.REGISTRY.get_sample_value("hft_ingest_to_signal_seconds_sum") or 0.0
    prom.observe_latency_sample(
        LatencySample(ingest_to_signal_ns=2_000_000_000, signal_compute_ns=0, order_round_trip_ns=None)
    )
    after = prom.REGISTRY.get_sample_value("hft_ingest_to_signal_seconds_sum")
    assert after - before == pytest.approx(2.0)


def test_an_order_round_trip_is_only_observed_when_one_happened():
    # A tick that produces no signal has no order round trip, and recording a
    # zero for it would drag the whole distribution down.
    before = prom.REGISTRY.get_sample_value("hft_order_round_trip_seconds_count") or 0.0
    prom.observe_latency_sample(
        LatencySample(ingest_to_signal_ns=100, signal_compute_ns=50, order_round_trip_ns=None)
    )
    after = prom.REGISTRY.get_sample_value("hft_order_round_trip_seconds_count")
    assert after == before


def test_rejection_reasons_stay_a_bounded_label_set():
    # The label is documented as an exception *type* name. A formatted message
    # with an id or a price in it would make the series unbounded.
    prom.record_order_rejected(type(ValueError("order 12345 too large")).__name__)
    assert prom.REGISTRY.get_sample_value("hft_orders_rejected_total", {"reason": "ValueError"}) is not None
